#define EC_FW_VERSION_ADDRESS 0xA0
#define EC_FW_VERSION_LENGTH 12

#define EC_KBD_BACKLIGHT_ADDRESS_STATE 0xD3
#define EC_KBD_BACKLIGHT_MAX_STATE 3

#define EC_KBD_AUDIOMUTE_LED_ADDRESS 0x2C
#define EC_KBD_AUDIOMUTE_LED_BIT 2

#define EC_KBD_MICMUTE_LED_ADDRESS 0x2B
#define EC_KBD_MICMUTE_LED_BIT 2
